global:
  scrape_interval: 15s  # 메트릭 스크랩 간격 15초

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # Prometheus 자체

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']  # node_exporter 서비스

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysqld_exporter:9104']  # mysqld_exporter 서비스


# 이건 proxy_exporter.yml
#   - job_name: 'proxysql'
#     static_configs:
#       - targets: ['proxy_sql_exporter:9104']  # ProxySQL Exporter 서비스
